METHOD:
    steps_pnp: 100
    lr_pnp: 1.0
    gamma_style: 'alpha_1_minus_t'
    num_samples: 5
    alpha: 0.01
    interpolation_mode: 'random'
    datafit_mode: 'gd' # 'gd' for gd step on datafit 'prox' for prox step
    denoise_mode: 'gd' # 'gd' for PnP-Flow 'prox' for Approx-PGD 